// Local UI verification only. No Google login or cloud writes are performed.
// Automated regression uses Playwright; final interactive Browser verification is separate.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.HOUSEHOLD_PLAYWRIGHT_MODULE || 'playwright');
const origin = process.env.HOUSEHOLD_PREVIEW_URL || 'http://127.0.0.1:4283';
const output = process.env.HOUSEHOLD_QA_OUTPUT || path.join(os.tmpdir(),'household-ui-qa');
await mkdir(output,{recursive:true});
const browser = await chromium.launch({headless:true,channel:process.env.HOUSEHOLD_BROWSER_CHANNEL || 'chrome'});
const context = await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});
const page = await context.newPage();
const failures=[];
page.on('pageerror',error=>failures.push(error.message));
page.on('console',msg=>{if(msg.type()==='error'&&!/404.*Not Found/.test(msg.text()))failures.push(msg.text());});
await page.route('**/runtime-config.json',route=>route.fulfill({status:404,body:'Not configured'}));
let source=(await readFile(new URL('../web/transport.js',import.meta.url),'utf8')).replace(/\r\n/g,'\n');
source=source.replace('state = response.state;\n    return copy(response);','state = response.state;\n    if(command.type === "saveIncome" && !globalThis.__lostIncomeResponse){globalThis.__lostIncomeResponse=true;throw Object.assign(new Error("通信テスト: 保存結果を確認できません。"),{code:"TIMEOUT"});}\n    return copy(response);');
source=source.replace('const response = globalThis.HouseholdDomain.execute(state, copy(command));',`if(command.type==='upsertExpense'&&command.payload.description==='スーパー'){
  globalThis.__conflictRevisions??=[];globalThis.__conflictRevisions.push(command.expectedRevision);
  globalThis.__conflictIds??=[];globalThis.__conflictIds.push(command.operationId);
  if(!globalThis.__firstExpenseTimeout){globalThis.__firstExpenseTimeout=true;throw Object.assign(new Error('通信テスト: 保存結果を確認できません。'),{code:'TIMEOUT'});}
  if(!globalThis.__serverConflict){globalThis.__serverConflict=true;state=globalThis.HouseholdDomain.execute(state,{type:'saveBill',payload:{month:'2026-09',confirmedAmount:0},operationId:crypto.randomUUID()}).state;throw Object.assign(new Error('別の保存が反映されています。再読み込み後にやり直してください。'),{code:'CONFLICT'});}
}
const response = globalThis.HouseholdDomain.execute(state, copy(command));`);
await page.route('**/web/transport.js',route=>route.fulfill({contentType:'text/javascript',body:source}));
// Expose integration entry points only in this intercepted test copy, never production source.
let appSource=(await readFile(new URL('../web/app.js',import.meta.url),'utf8')).replace(/\r\n/g,'\n');
appSource=appSource.replace('\nawait initializeConfig();\n','\nglobalThis.__householdTest={transport:()=>transport,refresh:async()=>{state=await transport.load();render();}};\nawait initializeConfig();\n');
await page.route('**/web/app.js',route=>route.fulfill({contentType:'text/javascript',body:appSource}));
const importFixture=payload=>page.evaluate(async input=>{
  const harness=globalThis.__householdTest,transport=harness.transport(),current=await transport.load();
  await transport.mutate({type:'importReceipt',payload:input,operationId:crypto.randomUUID(),expectedRevision:current.revision});
  await harness.refresh();
},payload);
const click = (name) => page.getByRole('button',{name,exact:true}).click();
const waitSaved=async()=>{await page.getByRole('status').filter({hasText:'保存しました。'}).waitFor();};
const form = id => page.locator('#'+id);
try {
  await page.goto(origin,{waitUntil:'networkidle'});
  assert.equal(await page.title(),'家計簿');
  await page.getByText('Google連携の準備が必要です。',{exact:false}).waitFor();
  await page.screenshot({path:path.join(output,'01-setup-mobile.png'),fullPage:true});
  await click('サンプルで試す');
  assert.equal(await page.locator('[data-page=register]').getAttribute('aria-current'),'page');
  assert.equal(await page.getByRole('tab',{name:'レシート',exact:true}).getAttribute('aria-selected'),'true');
  await click('ホーム');
  await page.locator('.ledger-main').waitFor();
  assert.equal(await page.locator('.big-money').innerText(),'¥0');
  assert.equal(await page.evaluate(async()=>(await globalThis.__householdTest.transport().load()).revision),0,'Empty month must not cause a save');
  await page.locator('#month').fill('2026-10');
  await click('毎月の設定');
  const totals=()=>page.locator('[data-setting-total]');
  assert.deepEqual(await totals().allTextContents(),['¥0','¥0']);
  let f=form('setting-form');
  await f.locator('[name=kind]').selectOption('saving');
  await f.locator('[name=name]').fill('家電積立');
  await f.locator('[name=plannedAmount]').fill('10000');
  await f.locator('[name=openingBalance]').fill('50000');
  await f.getByRole('button',{name:'項目を追加'}).click();
  await page.locator('.monthly-form').waitFor();
  f=form('setting-form');
  await f.locator('[name=name]').fill('家賃');
  await f.locator('[name=paymentMethod]').selectOption('cash');
  await f.locator('[name=plannedAmount]').fill('70000');
  await f.getByRole('button',{name:'項目を追加'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.setting-row').length===2&&document.querySelector('#main').getAttribute('aria-busy')==='false');
  assert.equal(await page.locator('.monthly-form').count(),1,'Monthly list contains savings only');
  assert.deepEqual(await totals().allTextContents(),['¥10,000','¥70,000']);
  assert.deepEqual(await page.locator('[data-setting-kind]').evaluateAll(nodes=>nodes.map(n=>n.dataset.settingKind)),['saving','fixed']);
  assert.equal(await page.locator('[data-setting-kind=fixed] .setting-row').filter({hasText:'家賃'}).count(),1);
  assert.equal(await page.locator('[data-setting-kind=saving] .setting-row').filter({hasText:'家電積立'}).count(),1);
  const rentSetting=page.locator('.setting-row').filter({hasText:'家賃'});
  await rentSetting.getByRole('button',{name:'停止',exact:true}).click();await waitSaved();
  assert.deepEqual(await totals().allTextContents(),['¥10,000','¥0']);
  await rentSetting.getByRole('button',{name:'再開',exact:true}).click();await waitSaved();
  assert.deepEqual(await totals().allTextContents(),['¥10,000','¥70,000']);
  await page.locator('.setting-row').filter({hasText:'家電積立'}).getByRole('button',{name:'編集',exact:true}).click();
  await form('setting-form').locator('[name=plannedAmount]').fill('11000');
  await form('setting-form').getByRole('button',{name:'設定を保存'}).click();await waitSaved();
  assert.deepEqual(await totals().allTextContents(),['¥11,000','¥70,000']);
  assert.equal(await page.locator('.monthly-form').filter({hasText:'家電積立'}).locator('[name=plannedAmount]').inputValue(),'10000');
  await page.locator('#month').fill('2026-11');
  await page.waitForFunction(()=>document.querySelector('.monthly-form [name=plannedAmount]')?.value==='11000');
  await page.locator('#month').fill('2026-10');
  await page.waitForFunction(()=>document.querySelector('.monthly-form [name=plannedAmount]')?.value==='10000');
  await click('ホーム');
  await click('給与を入力');
  await form('income-form').locator('[name=amount]').fill('300000');
  await form('income-form').getByRole('button',{name:'給与を保存'}).click();
  await page.locator('#pending').waitFor({state:'visible'});
  assert.equal(await form('income-form').locator('[name=amount]').inputValue(),'300000');
  await click('同じ内容で再試行');
  await waitSaved();
  assert.equal(await page.locator('.big-money').innerText(),'¥230,000');
  await click('登録');await page.getByRole('tab',{name:'支出',exact:true}).click();
  await page.locator('#month').fill('2026-09');
  let registration=form('expense-form');
  const todayDate=await page.evaluate(()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));
  assert.equal(await registration.locator('[name=useDate]').inputValue(),todayDate);
  assert.equal(await registration.locator('[name=accountingMonth]').inputValue(),todayDate.slice(0,7));
  const selectablePlanIds=await registration.locator('[name=planId] option').evaluateAll(nodes=>nodes.map(node=>node.value).filter(Boolean));
  assert.equal(await page.evaluate(async ids=>(await globalThis.__householdTest.transport().load()).plans.filter(plan=>ids.includes(plan.id)).every(plan=>plan.month===new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit'}).format(new Date())),selectablePlanIds),true);
  await registration.locator('[name=useDate]').fill('2026-09-30');
  assert.equal(await registration.locator('[name=planId] option').count(),1,'Changing accounting month removes foreign fixed plans');
  await registration.locator('[name=useDate]').fill(todayDate);
  assert.equal(await registration.locator('.expense-options').getAttribute('open'),null);
  await registration.locator('[name=amount]').fill('25');
  await registration.locator('[name=description]').fill('今日の支出');
  await registration.getByRole('button',{name:'支出を保存'}).click();await waitSaved();
  await page.getByRole('status').filter({hasText:'計上月は'}).waitFor();
  await click('履歴');assert.equal(await page.locator('.entry').filter({hasText:'今日の支出'}).count(),0);
  await page.locator('#month').fill(todayDate.slice(0,7));
  await page.locator('.entry').filter({hasText:'今日の支出'}).waitFor();
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('.entry').filter({hasText:'今日の支出'}).getByRole('button',{name:'削除',exact:true}).click();await waitSaved();
  await page.locator('#month').fill('2026-10');await click('登録');await page.getByRole('tab',{name:'支出',exact:true}).click();
  await page.screenshot({path:path.join(output,'06-register-mobile.png'),fullPage:true});
  f=form('expense-form');
  await f.locator('[name=useDate]').fill('2026-10-03');
  await f.locator('[name=amount]').fill('2500');
  await f.locator('[name=description]').fill('スーパー');
  await f.getByRole('button',{name:'支出を保存'}).click();
  await page.locator('#pending').waitFor({state:'visible'});
  await click('同じ内容で再試行');
  await page.getByRole('alert').filter({hasText:'最新情報を読み込みました。'}).waitFor();
  await page.locator('#pending').waitFor({state:'hidden'});
  assert.equal(await f.locator('[name=amount]').inputValue(),'2500');
  assert.equal(await f.locator('[name=description]').inputValue(),'スーパー');
  await f.getByRole('button',{name:'支出を保存'}).click();await waitSaved();
  const conflictRevisions=await page.evaluate(()=>globalThis.__conflictRevisions);
  assert.equal(conflictRevisions.length,3);
  assert.equal(conflictRevisions[1],conflictRevisions[0],'Ambiguous network retry retains revision');
  assert.equal(conflictRevisions[2],conflictRevisions[0]+1,'Confirmed conflict releases the stale retry and next save uses the reloaded revision');
  const conflictIds=await page.evaluate(()=>globalThis.__conflictIds);
  assert.equal(conflictIds[0],conflictIds[1]);
  assert.notEqual(conflictIds[1],conflictIds[2]);
  f=form('expense-form');
  await f.locator('[name=useDate]').fill('2026-10-01');
  await f.locator('.expense-options summary').click();
  assert.equal(await f.locator('[name=planId] option').count(),1,'Automatically paid fixed plans are not offered as unpaid');
  await click('履歴');
  const rent=page.locator('.entry').filter({hasText:'家賃'});
  await rent.getByText('固定費 · 現金',{exact:false}).waitFor();
  const rentActual=await page.evaluate(async()=>(await globalThis.__householdTest.transport().load()).expenses.filter(e=>e.description==='家賃'&&e.accountingMonth==='2026-10'&&!e.deleted));
  assert.equal(rentActual.length,1);assert.equal(rentActual[0].useDate,'2026-10-01');
  page.once('dialog',dialog=>dialog.accept());
  await rent.getByRole('button',{name:'削除',exact:true}).click();await waitSaved();
  await click('登録');await page.getByRole('tab',{name:'支出',exact:true}).click();
  f=form('expense-form');
  await f.locator('[name=useDate]').fill('2026-08-28');
  await f.locator('[name=paymentMethod]').selectOption('card');
  assert.equal(await f.locator('[name=accountingMonth]').inputValue(),'2026-10');
  await f.locator('[name=amount]').fill('12000');
  await f.locator('[name=category]').selectOption('必要経費');
  await f.locator('[name=description]').fill('炊飯器');
  await f.locator('.expense-options summary').click();
  const savingId=await f.locator('[name=fundingSettingId] option').nth(1).getAttribute('value');
  await f.locator('[name=fundingSettingId]').selectOption(savingId);
  await f.getByRole('button',{name:'支出を保存'}).click();await waitSaved();
  await page.getByRole('tab',{name:'積立',exact:true}).click();
  f=form('transfer-form');
  await f.locator('[name=settingId]').selectOption(savingId);
  await f.locator('[name=amount]').fill('5000');
  await f.locator('[name=date]').fill('2026-10-04');
  await f.getByRole('button',{name:'実際の移動を保存'}).click();await waitSaved();
  await click('ホーム');
  assert.equal(await page.locator('.big-money').innerText(),'¥280,500');
  const outflow=page.locator('#outflow-breakdown');
  const outflowCategory=name=>outflow.locator('details').filter({has:page.locator(`summary>span`).filter({hasText:new RegExp(`^${name}$`)})});
  assert.equal(await outflow.locator('[data-outflow-total]').innerText(),'¥19,500');
  assert.equal(await outflowCategory('積立').locator('summary strong').innerText(),'¥5,000');
  assert.equal(await outflowCategory('必要経費').locator('summary strong').innerText(),'¥12,000');
  assert.equal(await page.locator('.saving-row').filter({hasText:'家電積立'}).locator('strong.number').innerText(),'¥55,000');
  await click('支払い確認・取り崩し');
  f=form('transfer-form');assert.equal(await f.locator('[name=amount]').inputValue(),'12000');
  assert.equal(await page.locator('#transfer-current-balance').innerText(),'¥55,000');
  assert.equal(await page.locator('#transfer-after-balance').innerText(),'¥43,000');
  const linkedCardId=await f.locator('[name=expenseId]').inputValue();
  assert.ok(linkedCardId,'Initial withdrawal remains linked to purchase');
  await f.locator('[name=amount]').fill('4000');
  assert.equal(await page.locator('#transfer-after-balance').innerText(),'¥51,000');
  await f.locator('[name=date]').fill('2026-10-05');
  await f.getByRole('button',{name:'実際の移動を保存'}).click();await waitSaved();
  await click('ホーム');
  assert.equal(await page.locator('.saving-row').filter({hasText:'家電積立'}).locator('strong.number').innerText(),'¥51,000');
  assert.equal(await outflowCategory('必要経費').locator('summary strong').innerText(),'¥8,000');
  await outflowCategory('必要経費').locator('summary').click();
  await outflowCategory('必要経費').getByText('炊飯器',{exact:true}).waitFor();
  assert.equal(await outflowCategory('必要経費').locator('.outflow-entry strong').innerText(),'¥8,000');
  await outflowCategory('必要経費').locator('summary').click();
  await click('支払い確認・取り崩し');
  f=form('transfer-form');
  assert.equal(await f.locator('[name=amount]').inputValue(),'8000','Remainder action presets only the unwithdrawn amount');
  assert.equal(await f.locator('[name=expenseId]').inputValue(),linkedCardId,'Partial withdrawal does not remove the purchase option');
  assert.equal(await f.locator('[name=settingId]').inputValue(),savingId);
  await f.locator('[name=expenseId]').selectOption('');
  await f.locator('[name=amount]').fill('1');
  await f.locator('[name=expenseId]').selectOption(linkedCardId);
  assert.equal(await f.locator('[name=amount]').inputValue(),'8000','Ordinary purchase selection also uses remaining amount');
  assert.equal(await page.locator('#transfer-current-balance').innerText(),'¥51,000');
  assert.equal(await page.locator('#transfer-after-balance').innerText(),'¥43,000');
  assert.equal(await f.locator('[name=kind]').inputValue(),'withdrawal');
  await f.locator('[name=date]').fill('2026-10-05');
  await f.getByRole('button',{name:'実際の移動を保存'}).click();await waitSaved();
  const linkedWithdrawals=await page.evaluate(async id=>(await globalThis.__householdTest.transport().load()).transfers.filter(t=>t.expenseId===id),linkedCardId);
  assert.equal(linkedWithdrawals.length,2);
  assert.equal(linkedWithdrawals.reduce((total,t)=>total+t.amount,0),12000);
  await click('ホーム');
  assert.equal(await page.locator('.saving-row').filter({hasText:'家電積立'}).locator('strong.number').innerText(),'¥43,000');
  assert.equal(await page.locator('.big-money').innerText(),'¥292,500');
  assert.equal(await page.getByRole('button',{name:'支払い確認・取り崩し'}).count(),0);
  assert.equal(await outflow.locator('[data-outflow-total]').innerText(),'¥7,500');
  assert.equal(await outflowCategory('必要経費').locator('summary strong').innerText(),'¥0');
  let requestsDuringExpansion=0;
  const countExpansion=()=>requestsDuringExpansion++;
  page.on('request',countExpansion);
  await context.setOffline(true);
  await outflowCategory('積立').locator('summary').click();
  await outflowCategory('積立').getByText('家電積立',{exact:true}).waitFor();
  assert.equal(await outflowCategory('積立').locator('.outflow-entry strong').innerText(),'¥5,000');
  await outflowCategory('積立').locator('summary').focus();
  await page.keyboard.press('Space');assert.equal(await outflowCategory('積立').getAttribute('open'),null);
  await page.keyboard.press('Enter');assert.notEqual(await outflowCategory('積立').getAttribute('open'),null);
  assert.equal(requestsDuringExpansion,0,'Opening/closing the local breakdown sends no requests, even offline');
  page.off('request',countExpansion);await context.setOffline(false);
  await form('bill-form').locator('[name=confirmedAmount]').fill('12000');
  await form('bill-form').getByRole('button',{name:'請求額を保存'}).click();await waitSaved();
  assert.notEqual(await outflowCategory('積立').getAttribute('open'),null,'In-place redraw retains expanded category');
  assert.equal(await page.locator('.big-money').innerText(),'¥292,500');
  await page.screenshot({path:path.join(output,'02-home-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await click('履歴');
  const supermarket=page.locator('.entry').filter({hasText:'スーパー'});
  await supermarket.getByRole('button',{name:'編集',exact:true}).click();
  await form('expense-form').locator('[name=amount]').fill('3000');
  await form('expense-form').getByRole('button',{name:'変更を保存'}).click();await waitSaved();
  await click('履歴');
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('.entry').filter({hasText:'スーパー'}).getByRole('button',{name:'削除',exact:true}).click();await waitSaved();
  assert.equal(await page.locator('.entry').filter({hasText:'スーパー'}).count(),0);
  await click('登録');assert.equal(await page.getByRole('tab',{name:'レシート'}).getAttribute('aria-selected'),'true');
  await form('receipt-form').locator('[name=image]').setInputFiles({name:'sample.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlFkAAAAASUVORK5CYII=','base64')});
  await form('receipt-form').getByRole('button',{name:'画像を保存'}).click();await waitSaved();
  assert.equal(await page.locator('#import-form').count(),0);
  assert.equal(await page.locator('#saved-receipts').getAttribute('open'),null);
  await page.locator('#saved-receipts>summary').click();
  await page.getByText('購入日：未確認',{exact:false}).waitFor();
  const receiptId=await page.evaluate(async()=>(await globalThis.__householdTest.transport().load()).receipts.at(-1).id);
  await click('画像を見る');await page.locator('.private-image').waitFor();
  assert.equal(await page.locator('#saved-receipts-content .private-image').count(),1);
  await click('閉じる');
  const imported={receiptId,merchant:'ヨーカドー',useDate:'2026-10-04',paymentMethod:'cash',total:960,lines:[{lineId:'lemon',amount:130,quantity:1,category:'酒',description:'レモンサワー'},{lineId:'beer',amount:350,quantity:2,category:'酒',description:'一番搾り'},{lineId:'food',amount:480,quantity:1,category:'食費',description:'トンカツ'}]};
  await importFixture({...imported,total:999});
  await page.getByText('確認待ち',{exact:true}).waitFor();
  await page.getByText('レシート合計と明細の合計が一致しません。',{exact:false}).waitFor();
  await importFixture(imported);
  await page.getByText('取込済み',{exact:true}).waitFor();
  await page.getByText('購入日：2026-10-04',{exact:false}).waitFor();
  await page.getByText('保存日時：',{exact:false}).waitFor();
  await click('履歴');
  const receiptPurchase=page.locator('.entry').filter({hasText:'ヨーカドー'});
  assert.equal(await receiptPurchase.count(),1,'One receipt produces one purchase row');
  assert.equal(await receiptPurchase.locator('.entry-right strong').innerText(),'¥960');
  await receiptPurchase.getByRole('button',{name:'10/04 ヨーカドーの詳細'}).click();
  const details=page.getByRole('dialog',{name:'ヨーカドー'});
  assert.equal(await details.locator('.purchase-item').count(),3);
  assert.equal(await details.locator('.purchase-item').filter({hasText:'一番搾り'}).locator('strong').innerText(),'¥350','Quantity2 is already included in line total');
  await details.getByText('酒 × 2 · 現金',{exact:true}).waitFor();
  await details.getByRole('button',{name:'レシート画像を見る'}).click();
  await details.locator('.private-image').waitFor();
  await details.getByRole('button',{name:'閉じる',exact:true}).last().click();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(),0);
  assert.equal(await receiptPurchase.getByRole('button',{name:'10/04 ヨーカドーの詳細'}).evaluate(el=>el===document.activeElement),true,'Escape returns focus to purchase row');
  await page.evaluate(()=>{
    const t=globalThis.__householdTest.transport();
    globalThis.__receiptImageOriginal=t.receiptImage.bind(t);
    t.receiptImage=async()=>{throw new Error('画像の取得に失敗しました。');};
  });
  await receiptPurchase.getByRole('button',{name:'10/04 ヨーカドーの詳細'}).click();
  await details.getByRole('button',{name:'レシート画像を見る'}).click();
  await details.getByRole('alert').filter({hasText:'画像の取得に失敗しました。'}).waitFor();
  assert.equal(await details.getByRole('button',{name:'レシート画像を見る'}).isEnabled(),true,'Image error permits retry');
  await page.evaluate(()=>{globalThis.__householdTest.transport().receiptImage=async id=>{await new Promise(resolve=>globalThis.__releaseImage=resolve);return globalThis.__receiptImageOriginal(id);};});
  await details.getByRole('button',{name:'レシート画像を見る'}).click();
  assert.equal(await details.getByRole('button',{name:'画像を読み込み中…'}).isEnabled(),false);
  await page.keyboard.press('Escape');
  await page.evaluate(async id=>{globalThis.__releaseImage();await globalThis.__receiptImageOriginal(id);globalThis.__householdTest.transport().receiptImage=globalThis.__receiptImageOriginal;},receiptId);
  assert.equal(await page.locator('.private-image').count(),0,'Late image must not appear after detail dismissal');
  await receiptPurchase.getByRole('button',{name:'10/04 ヨーカドーの詳細'}).click();
  await details.locator('.purchase-item').filter({hasText:'一番搾り'}).getByRole('button',{name:'編集',exact:true}).click();
  assert.equal(await page.getByRole('dialog').count(),0,'Editing closes detail dialog');
  await form('expense-form').locator('[name=amount]').fill('370');
  await form('expense-form').locator('[name=quantity]').fill('3');
  await form('expense-form').locator('[name=paymentMethod]').selectOption('bank');
  await form('expense-form').getByRole('button',{name:'変更を保存'}).click();await waitSaved();
  await page.getByRole('tab',{name:'レシート'}).click();
  await importFixture(imported);
  await click('履歴');
  assert.equal(await receiptPurchase.count(),1);
  assert.equal(await receiptPurchase.locator('.entry-right strong').innerText(),'¥980');
  await receiptPurchase.getByRole('button',{name:'10/04 ヨーカドーの詳細'}).click();
  const beer=details.locator('.purchase-item').filter({hasText:'一番搾り'});
  assert.equal(await beer.locator('strong').innerText(),'¥370');
  await beer.getByText('酒 × 3 · 銀行',{exact:true}).waitFor();
  await receiptPurchase.getByText('3明細 · 現金・銀行',{exact:false}).waitFor({state:'attached'});
  for(const width of [320,375,414,768]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await details.evaluate(el=>el.scrollWidth>el.clientWidth),false,'Detail dialog must fit');}
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'10-receipt-purchase-detail.png'),fullPage:true});
  await details.getByRole('button',{name:'閉じる',exact:true}).click();
  await page.screenshot({path:path.join(output,'03-history-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1280,height:900});await click('ホーム');
  await page.screenshot({path:path.join(output,'04-home-desktop.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  for(const width of [320,375,414,768]){
    await page.setViewportSize({width,height:844});
    await page.screenshot({path:path.join(output,`05-home-${width}.png`),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`horizontal overflow at ${width}`);
    const wrapped=await page.locator('button').evaluateAll(buttons=>buttons.filter(button=>{
      if(!button.offsetParent || button.querySelector('span'))return false;
      const range=document.createRange();range.selectNodeContents(button);
      const lines=new Set([...range.getClientRects()].map(rect=>Math.round(rect.top)));
      return lines.size>1;
    }).map(button=>button.textContent));
    assert.deepEqual(wrapped,[],`wrapped button at ${width}`);
    for(const name of ['登録','履歴','毎月の設定']){
      await click(name);
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name} horizontal overflow at ${width}`);
    }
    await click('ホーム');
  }
  const storage=await page.evaluate(async()=>({local:localStorage.length,session:sessionStorage.length,db:typeof indexedDB.databases==='function'?(await indexedDB.databases()).length:0}));
  assert.deepEqual(storage,{local:0,session:0,db:0});
  await click('ログアウト');await click('サンプルで試す');
  await click('ホーム');
  await page.locator('#month').fill('2026-10');
  await page.evaluate(async()=>{
    const t=globalThis.__householdTest.transport();
    for(const [type,payload] of [
      ['saveSetting',{id:'sample-saving',kind:'saving',name:'50万円の積立（サンプル）',plannedAmount:0,openingBalance:500000}],
      ['saveIncome',{month:'2026-10',amount:300000}],
      ['upsertExpense',{id:'sample-purchase',useDate:'2026-10-05',amount:500000,paymentMethod:'cash',category:'必要経費',fundingSettingId:'sample-saving',description:'積立から50万円の購入（サンプル）'}]
    ]){const current=await t.load();await t.mutate({type,payload,operationId:crypto.randomUUID(),expectedRevision:current.revision});}
    await globalThis.__householdTest.refresh();
  });
  await page.getByText('今月の残り',{exact:true}).waitFor();
  await page.getByText('積立で賄う購入の取り崩しが',{exact:false}).waitFor();
  await click('取り崩しを記録');
  f=form('transfer-form');
  assert.equal(await page.locator('#transfer-current-balance').innerText(),'¥500,000');
  assert.equal(await page.locator('#transfer-after-balance').innerText(),'¥0');
  await f.locator('[name=amount]').fill('500001');
  assert.equal(await page.locator('#transfer-after-balance').innerText(),'¥-1');
  assert.equal(await page.locator('#transfer-after-balance.negative').count(),1);
  await f.locator('[name=amount]').fill('500000');
  assert.equal(await f.locator('[name=amount]').inputValue(),'500000');
  assert.equal(await f.locator('[name=expenseId]').inputValue(),'sample-purchase');
  await f.locator('[name=date]').fill('2026-10-05');
  await f.getByRole('button',{name:'実際の移動を保存'}).click();await waitSaved();
  await click('ホーム');
  assert.equal(await page.locator('.big-money').innerText(),'¥300,000','Salary300k, purchase500k funded by saving500k leaves salary300k');
  assert.equal(await page.locator('.saving-row').filter({hasText:'50万円の積立（サンプル）'}).locator('strong.number').innerText(),'¥0');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'09-saving-funded-example.png'),fullPage:true});
  await click('ログアウト');await click('サンプルで試す');
  assert.equal(await page.locator('[data-page=register]').getAttribute('aria-current'),'page');
  assert.equal(await page.getByRole('tab',{name:'レシート',exact:true}).getAttribute('aria-selected'),'true');
  await click('ホーム');
  assert.equal(await page.locator('.big-money').innerText(),'¥0');
  assert.equal(await page.getByText('炊飯器',{exact:true}).count(),0);
  assert.deepEqual(failures,[]);
  console.log('PASS: setup, empty demo, monthly snapshots, income ambiguous retry, expenses, card-funded withdrawal, bill reconciliation, edit/delete tombstone, receipt upload/image/status/integration fixtures, logout privacy, mobile/desktop.');
  console.log('Screenshots: '+output);
} finally {await browser.close();}
